// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lesson2_17_09_25;

#nullable disable

namespace lesson2_17_09_25.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250924154143_InitStudents")]
    partial class InitStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("lesson2_17_09_25.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VkProfileLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 24, 18, 41, 43, 489, DateTimeKind.Unspecified).AddTicks(2459), new TimeSpan(0, 3, 0, 0, 0)),
                            Email = "vanya123@gmail.com",
                            FirstName = "Иван",
                            LastName = "Иванов",
                            Login = "vanya123",
                            MiddleName = "Иванович",
                            VkProfileLink = "https://vk.com/vanya123",
                            phoneNumber = "+7149312931893"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 24, 18, 41, 43, 491, DateTimeKind.Unspecified).AddTicks(7321), new TimeSpan(0, 3, 0, 0, 0)),
                            Email = "maria123@gmail.com",
                            FirstName = "Мария",
                            LastName = "Иванов",
                            Login = "maria123",
                            MiddleName = "Иванович",
                            VkProfileLink = "https://vk.com/maria123",
                            phoneNumber = "+78932179832"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
